name: CI/CD Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Configure default region
        run: gcloud config set run/region ${{ secrets.GCP_REGION }}

      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-service \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-app \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars SQLALCHEMY_DATABASE_URL=${{ secrets.SQLALCHEMY_DATABASE_URL }}
